export * from "./edu/student";
export * from "./edu/course";
export * from "./edu/class";
export * from "./edu/room";
export * from "./edu/term";
export * from "./edu/benefit";
export * from "./edu/schedule";
export * from "./edu/lesson-completion";
export * from "./edu/statistics";
